# Generated by Django 4.1.7 on 2023-04-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='image',
            field=models.ImageField(blank=True, default='pngtree-blue-default-avatar-png-image_2813123.jpg', null=True, upload_to='image/'),
        ),
    ]
